import type { MedicalYear, QuizLanguage, RoomSettings } from "@/lib/types";

// Broad undergraduate subject catalog; exact year placement varies by faculty.
export const medicalSubjects = [
  "mixed",
  "anatomy",
  "physiology",
  "histology",
  "biochemistry",
  "medical_biology",
  "genetics",
  "biophysics",
  "biostatistics",
  "microbiology",
  "immunology",
  "parasitology",
  "pathology",
  "pharmacology",
  "internal",
  "cardiology",
  "pulmonology",
  "gastroenterology",
  "endocrinology",
  "nephrology",
  "hematology",
  "oncology",
  "rheumatology",
  "geriatrics",
  "infectious",
  "pediatrics",
  "neurology",
  "psychiatry",
  "child_psychiatry",
  "dermatology",
  "rehabilitation",
  "radiology",
  "nuclear_medicine",
  "radiation_oncology",
  "sports_medicine",
  "surgery",
  "obgyn",
  "pediatric_surgery",
  "neurosurgery",
  "cardiovascular_surgery",
  "thoracic_surgery",
  "orthopedics",
  "urology",
  "ent",
  "ophthalmology",
  "plastic_surgery",
  "anesthesiology",
  "emergency",
  "intensive_care",
  "family_medicine",
  "public_health",
  "forensic",
  "ethics_history",
  "clinical_skills",
  "evidence_based",
  "medical_informatics",
] as const;
export type MedicalSubject = (typeof medicalSubjects)[number];

export const medicalSubjectLabels: Record<QuizLanguage, Record<MedicalSubject, string>> = {
  tr: {
    mixed: "Tüm dersler",
    anatomy: "Anatomi",
    physiology: "Fizyoloji",
    histology: "Histoloji ve Embriyoloji",
    biochemistry: "Tıbbi Biyokimya",
    medical_biology: "Tıbbi Biyoloji",
    genetics: "Tıbbi Genetik",
    biophysics: "Biyofizik",
    biostatistics: "Biyoistatistik",
    microbiology: "Tıbbi Mikrobiyoloji",
    immunology: "İmmünoloji",
    parasitology: "Tıbbi Parazitoloji",
    pathology: "Patoloji",
    pharmacology: "Tıbbi Farmakoloji",
    internal: "İç Hastalıkları (Dahiliye)",
    cardiology: "Kardiyoloji",
    pulmonology: "Göğüs Hastalıkları",
    gastroenterology: "Gastroenteroloji ve Hepatoloji",
    endocrinology: "Endokrinoloji ve Metabolizma",
    nephrology: "Nefroloji",
    hematology: "Hematoloji",
    oncology: "Tıbbi Onkoloji",
    rheumatology: "Romatoloji",
    geriatrics: "Geriatri",
    infectious: "Enfeksiyon Hastalıkları",
    pediatrics: "Çocuk Sağlığı ve Hastalıkları (Pediatri)",
    neurology: "Nöroloji",
    psychiatry: "Ruh Sağlığı ve Hastalıkları (Psikiyatri)",
    child_psychiatry: "Çocuk ve Ergen Ruh Sağlığı",
    dermatology: "Deri ve Zührevi Hastalıklar",
    rehabilitation: "Fiziksel Tıp ve Rehabilitasyon",
    radiology: "Radyoloji",
    nuclear_medicine: "Nükleer Tıp",
    radiation_oncology: "Radyasyon Onkolojisi",
    sports_medicine: "Spor Hekimliği",
    surgery: "Genel Cerrahi",
    obgyn: "Kadın Hastalıkları ve Doğum",
    pediatric_surgery: "Çocuk Cerrahisi",
    neurosurgery: "Beyin ve Sinir Cerrahisi",
    cardiovascular_surgery: "Kalp ve Damar Cerrahisi",
    thoracic_surgery: "Göğüs Cerrahisi",
    orthopedics: "Ortopedi ve Travmatoloji",
    urology: "Üroloji",
    ent: "Kulak Burun Boğaz Hastalıkları",
    ophthalmology: "Göz Hastalıkları",
    plastic_surgery: "Plastik, Rekonstrüktif ve Estetik Cerrahi",
    anesthesiology: "Anesteziyoloji ve Reanimasyon",
    emergency: "Acil Tıp",
    intensive_care: "Yoğun Bakım",
    family_medicine: "Aile Hekimliği",
    public_health: "Halk Sağlığı",
    forensic: "Adli Tıp",
    ethics_history: "Tıp Tarihi ve Etik",
    clinical_skills: "Mesleksel Beceriler ve Klinik İletişim",
    evidence_based: "Kanıta Dayalı Tıp ve Araştırma Yöntemleri",
    medical_informatics: "Tıbbi Bilişim",
  },
  en: {
    mixed: "All subjects",
    anatomy: "Anatomy",
    physiology: "Physiology",
    histology: "Histology and Embryology",
    biochemistry: "Medical Biochemistry",
    medical_biology: "Medical Biology",
    genetics: "Medical Genetics",
    biophysics: "Biophysics",
    biostatistics: "Biostatistics",
    microbiology: "Medical Microbiology",
    immunology: "Immunology",
    parasitology: "Medical Parasitology",
    pathology: "Pathology",
    pharmacology: "Medical Pharmacology",
    internal: "Internal Medicine",
    cardiology: "Cardiology",
    pulmonology: "Pulmonology",
    gastroenterology: "Gastroenterology and Hepatology",
    endocrinology: "Endocrinology and Metabolism",
    nephrology: "Nephrology",
    hematology: "Hematology",
    oncology: "Medical Oncology",
    rheumatology: "Rheumatology",
    geriatrics: "Geriatrics",
    infectious: "Infectious Diseases",
    pediatrics: "Pediatrics",
    neurology: "Neurology",
    psychiatry: "Psychiatry",
    child_psychiatry: "Child and Adolescent Psychiatry",
    dermatology: "Dermatology and Venereology",
    rehabilitation: "Physical Medicine and Rehabilitation",
    radiology: "Radiology",
    nuclear_medicine: "Nuclear Medicine",
    radiation_oncology: "Radiation Oncology",
    sports_medicine: "Sports Medicine",
    surgery: "General Surgery",
    obgyn: "Obstetrics and Gynecology",
    pediatric_surgery: "Pediatric Surgery",
    neurosurgery: "Neurosurgery",
    cardiovascular_surgery: "Cardiovascular Surgery",
    thoracic_surgery: "Thoracic Surgery",
    orthopedics: "Orthopedics and Traumatology",
    urology: "Urology",
    ent: "Otorhinolaryngology",
    ophthalmology: "Ophthalmology",
    plastic_surgery: "Plastic and Reconstructive Surgery",
    anesthesiology: "Anesthesiology and Reanimation",
    emergency: "Emergency Medicine",
    intensive_care: "Intensive Care",
    family_medicine: "Family Medicine",
    public_health: "Public Health",
    forensic: "Forensic Medicine",
    ethics_history: "History of Medicine and Ethics",
    clinical_skills: "Clinical Skills and Communication",
    evidence_based: "Evidence-Based Medicine and Research Methods",
    medical_informatics: "Medical Informatics",
  },
};

export const medicalSubjectGroups = [
  { id: "basic", label: { tr: "Temel Tıp Bilimleri", en: "Basic Medical Sciences" }, subjects: ["anatomy", "physiology", "histology", "biochemistry", "medical_biology", "genetics", "biophysics", "biostatistics", "microbiology", "immunology", "parasitology", "pathology", "pharmacology"] },
  { id: "clinical", label: { tr: "Dahili Tıp Bilimleri", en: "Clinical Medicine" }, subjects: ["internal", "cardiology", "pulmonology", "gastroenterology", "endocrinology", "nephrology", "hematology", "oncology", "rheumatology", "geriatrics", "infectious", "pediatrics", "neurology", "psychiatry", "child_psychiatry", "dermatology", "rehabilitation", "radiology", "nuclear_medicine", "radiation_oncology", "sports_medicine"] },
  { id: "surgical", label: { tr: "Cerrahi Tıp Bilimleri", en: "Surgical Medicine" }, subjects: ["surgery", "obgyn", "pediatric_surgery", "neurosurgery", "cardiovascular_surgery", "thoracic_surgery", "orthopedics", "urology", "ent", "ophthalmology", "plastic_surgery", "anesthesiology"] },
  { id: "practice", label: { tr: "Toplum Sağlığı ve Hekimlik Uygulamaları", en: "Community Health and Medical Practice" }, subjects: ["emergency", "intensive_care", "family_medicine", "public_health", "forensic", "ethics_history", "clinical_skills", "evidence_based", "medical_informatics"] },
] as const;

// Legacy rooms retain their cumulative scope until the host edits the selection.
export function selectedMedicalYears(settings: Pick<RoomSettings, "medicalYear" | "medicalYears">): MedicalYear[] {
  return settings.medicalYears ?? Array.from({ length: settings.medicalYear }, (_, index) => (index + 1) as MedicalYear);
}

export function medicalSelectionLabel(settings: Pick<RoomSettings, "medicalYear" | "medicalYears">, locale: QuizLanguage): string {
  const selected = selectedMedicalYears(settings);
  const parts = selected.map((year) => locale === "tr" ? `${year}.` : String(year));
  const years = parts.length === 1 ? parts[0] : `${parts.slice(0, -1).join(", ")}${locale === "tr" ? " ve " : " & "}${parts[parts.length - 1]}`;
  return locale === "tr" ? `Yalnızca ${years} sınıf` : `Only year${selected.length > 1 ? "s" : ""} ${years}`;
}
